apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-lab
  namespace: helm-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-lab
  template:
    metadata:
      labels:
        app: mariadb-lab
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: appdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: app1234
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-lab
  namespace: helm-lab
spec:
  selector:
    app: mariadb-lab
  ports:
    - port: 3306
      targetPort: 3306
