apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc-helm2
  labels:
    {{- include "flask-cicd-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard