{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - helm-lab
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-cicd-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
