apiVersion: v1
kind: Pod
metadata:
  name: image-loader
spec:
  containers:
    - name: loader
      image: docker:cli
      command: ["sleep", "300"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  restartPolicy: Never
