apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/flask-app

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi