{
 "title": "Flask CI/CD App Monitoring",
 "tags": [
  "flask",
  "cicd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_requests_total[1m])",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(flask_http_requests_total)" }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_requests_total{status=~\"5..\"}[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[5m]) / rate(flask_http_request_duration_seconds_count[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "MariaDB Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_ready{namespace=\"helm-lab\", pod=~\"mariadb-lab.*\", condition=\"true\"})",
     "legendFormat": "MariaDB"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"helm-lab\", pod=~\"flask-cicd-helm2.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"helm-lab\", pod=~\"flask-cicd-helm2.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}